name: 'Database migration'
author: 'guibranco'
description: 'Manage versioned SQL files for database migrations'

branding:
  icon: database
  color: green

inputs:
  operation:
    description: 'Which operation to execute. One of: dry-run, migrate, check, integrity'
    required: true
    default: 'migrate'
  driver:
    description: 'Which driver to use. One of: mysql, mariadb, postgresql, mssql, oracle11g'
    required: true
    default: 'mysql'
  host:
    description: 'Database host (domain or IPv4)'
    required: true
    default: '127.0.0.1'
  user:
    description: 'Database username'
    required: true
    default: 'root'
  database:
    description: 'Database name'
    required: true
    default: 'example'

outputs:
  time:
    description: 'The time we ran this action'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.operation }} ${{ inputs.driver }} ${{ inputs.host }} ${{ inputs.user }} ${{ inputs.database }}
